nerd-labs/mutambo

- deploy.sh
- package-lock.json
- package.json
> feat(github-pages): deploy to github pages

- src/components/Logo.vue
> fix(logo): fix logo position in footer

- package-lock.json
- package.json
- src/components/Create.vue
- src/components/Home.vue
- src/main.js
- src/store/index.js
- src/store/mutations.js
- src/store/plugins.js
Add basic vuex store setup
fixes #22
> feat(store): add vuex store + basic setup

- src/pages/create.vue
- src/pages/detail.vue
- src/router/index.js
- src/store/mutations.js
> feat(detail): add detail page

- src/pages/home.vue
> Feature/issue #50 add info to existing tournaments

- src/App.vue
- src/config.js
- src/pages/detail.vue
- src/pages/home.vue
- src/pages/league.vue
- src/pages/summary.vue
- src/pages/teams.vue
- src/router/index.js
- src/store/mutations.js
>  feat(routing): we now keep track of current progress

- src/components/match.vue
- src/helpers/berger.js
- src/pages/league.vue
- src/pages/summary.vue
- src/store/mutations.js
> feat(matches): save matches in store

- src/pages/detail.vue
- src/pages/home.vue
- src/pages/league.vue
- src/pages/random.vue
- src/pages/summary.vue
- src/pages/teams.vue
- src/store/getters.js
> refactor(getters): refactor tournament getters

- src/components/match.vue
- src/components/matches.vue
- src/components/table.vue
- src/config.js
- src/main.js
- src/pages/results.vue
- src/store/modules/league.js
- src/store/mutations.js
also provide edit match
fixes #73 
fixes #74
> feat(mut-table): create table component

- src/pages/league.vue
> fix(league): toggle between matches and table on league view

- package-lock.json
- package.json
- src/components/knockout-match.vue
- src/components/match.vue
- src/components/matches.vue
- src/helpers/match.js
- src/helpers/migrations.js
- src/pages/knockout.vue
- src/pages/teams.vue
- src/store/modules/knockout/actions.js
- src/store/modules/knockout/getters.js
- src/store/modules/knockout/mutations.js
- src/store/mutations.js
> feat(knockout): overview page

- src/config.js
- src/helpers/order-by-property.js
- src/helpers/shuffle.js
- src/helpers/table.js
- src/pages/create.vue
- src/pages/detail.vue
- src/pages/groupstage-draw.vue
- src/pages/groupstage.vue
- src/pages/summary.vue
- src/store/index.js
- src/store/modules/current-tournament.js
- src/store/modules/groupstage/actions.js
- src/store/modules/groupstage/getters.js
- src/store/modules/groupstage/index.js
- src/store/modules/groupstage/mutations.js
- src/store/modules/league.js
- src/store/mutations.js
> feat(groupstage): create groupstage

- src/pages/groupstage.vue
- src/store/modules/groupstage/getters.js
- src/store/modules/knockout/actions.js
- src/store/modules/knockout/getters.js
- src/store/modules/knockout/mutations.js
- src/store/mutations.js
also link groupstage to knockout + fix minor bug
fix #95
> fix(knockout): knockout now has it's own teams

- src/pages/groupstage-draw.vue
> feat(draw): fix draw animations

- src/App.vue
> feat(statusbar): add statusbar

- src/App.vue
- src/pages/home.vue
- src/style/style.css
> fix(home): super duper amount of teams

- src/pages/groupstage-draw.vue
- src/pages/groupstage.vue
> fix(groupstage): add table/matches toggle

- src/pages/home.vue
- src/pages/teams.vue
- src/style/style.css
> fix(random): checkbox layout fix

- src/pages/results.vue
> feat(result): add result page

- src/pages/groupstage.vue
fixes #128 
voorstel:
design kan nog gewijzigd worden ;) 
**top:**
**scrolled:**
> fix(groupstage): add shortcuts

- src/components/match.vue
- src/pages/knockout.vue
- src/pages/random.vue
- src/pages/results.vue
- src/store/mutations.js
> fix(knockout): fix knockout

- src/index.html
> feat(electron): add 'view' menu item to reload and toggle dev tools

- src/index.html
- src/pages/teams.vue
also comment automatic team generator
> feat(menu): add Edit menu item

- src/index.html
> feat(analytics): add tracking code

- src/components/match.vue
- src/pages/groupstage.vue
> fix(electron): electron issue styling

- src/components/knockout-match.vue
- src/pages/groupstage-draw.vue
- src/pages/knockout.vue
fixes #142 
fixes #143 
fixes #150
> fix(bugfixes) knockout and groupstage page

- src/components/knockout-match.vue
- src/store/modules/knockout/actions.js
fixes #167 ??
Bug looks fixed, but not sure if bugfix I did was the result of this fix... 🤷🏼‍♂️
#gohacks
> fix(knockout): fix bugs

- src/components/create-team.vue
- src/pages/teams.vue
fixes #161 
Debounce the emit of teams.. not the input #bugs
Also hide the continue button when not all teams are entered 👍
> fix(create-team): fix team data when entering to fast

- src/components/match.vue
> feat(match) error when tie not allowed

- src/pages/home.vue
- src/pages/knockout.vue
fixes #144 
also made a quick win fix #175
> feat(knockout): switch between matches and tree view + show correct icon on home page

- src/pages/random.vue
- src/pages/teams.vue
fixes #154 
🤷🏼‍♂️ wrong branch name, whoops 🙈
> feat(random) new layout

- src/pages/home.vue
- src/store/actions.js
- src/store/mutations.js
> feat(tournaments): delete tournaments

- src/components/header.vue
- src/config.js
- src/pages/create.vue
- src/pages/detail.vue
- src/pages/groupstage-draw.vue
- src/pages/random.vue
- src/pages/teams.vue
- src/router/index.js
- src/store/modules/current-tournament/getters.js
- src/store/mutations.js
> Feature/issue #106 back button

- src/style/style.css
Closes #183.
Issue was caused by having 
```css
align-items: center;
display: grid
```
on the parent, with 
```css
position: fixed;
```
on the child. 
Firefox tries to align this fixed child in the middle of the parent, while Chrome does not. I don't know why this was on the parent though, as it seems to have zero impact when you remove it.
Gitblame @RobbertWolfs.
> Feature/issue #183 bug layout firefox
